# ExploreGUI Installer for MacOs

This page provides instructions for creating an installer for MacOS Big Sur.

## Dependencies
- Python 3.8.12 and a virtual environment
- [PyInstaller](https://github.com/pyinstaller/pyinstaller) with `pip install pyinstaller==4.7` inside a the virtual environment.
- [Qt Installer Framework] (https://download.qt.io/official_releases/qt-installer-framework/4.2.0/)

## How to

- In a terminal activate the virtual environment and navigate to ExploreGUI folder.
- Install ExploreGUI using `pip install -e .`
- Run `pyinstaller --onedir --windowed --icon=MentalabLogo ExploreGUI_mac.spec`.

This should create a directory and an .app file both named `ExploreGUI` in the `dist` folder.
Right-click on the .app and select 'Show Package Contents' and access the directory `Contents/MacOS/explorepy`.
Go to the explorepy folder used in your environment (e.g. `/Users/usr_name/opt/anaconda3/envs/gui8/lib/python3.8/site-packages/explorepy`) and locate the file `btScan`.
Copy the `btScan` file and paste it into the `Contents/MacOS/explorepy` folder from the app bundle.
You can run the `ExploreGUI` app to make sure the software works as intended.


1. Install Qt Installer Framework and locate its directory (e.g. home/Qt/QtIFW).
2. Inside the QtIFW directory, locate the `binarycreator` file and copy its path.
3. Place all the contents of the `ExploreGUI` directory from the `dist` folder inside the `/installer/MacOs/ExploreGuiInstaller/ExploreGUI/packages/com.Mentalab.ExploreGUI/data` directory.
4. Open the `/installer/Ubuntu/ExploreGuiInstaller/ExploreGUI` folder in the terminal.
5. Run the command  `path_to_binarycreator -c config/config.xml -p packages --verbose  ExploreGUIInstaller`.
6. The installable file (`ExploreGUIInstaller.app`) will be located in the `/installer/Ubuntu/ExploreGuiInstaller/ExploreGUI` directory.
