name: building-offline
on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches:
      - master
      - develop
env:
  exploredesktop_path: 'installer/ExploreDesktopInstaller/ExploreDesktop/packages/com.Mentalab.ExploreDesktop/'
  config_path: 'installer/ExploreDesktopInstaller/ExploreDesktop/config/config.xml'
  package_path: 'installer/ExploreDesktopInstaller/ExploreDesktop/packages'
  usedevelop: 'true'
  usemacdevelop: 'true'
jobs:
  build:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    strategy:
      matrix:
        os: [ windows-latest, macos-latest ]
        python: [ 3.11.5 ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Switch to current branch
        run: git checkout ${{ env.BRANCH }}
      - name: Set up Python ${{ matrix.python }}
        uses: s-weigand/setup-conda@v1
        with:
          python-version: ${{ matrix.python }}
          conda-channels: anaconda, conda-forge, conda-canary
      - name: Install QT dependencies for windows
        if: matrix.os == 'windows-latest'
        run: |
          pip install aqtinstall
          python -m aqt install-qt -O ${{ github.workspace }}/Qt/ windows desktop 6.4.1 win64_msvc2019_64
          python -m aqt install-tool -O ${{ github.workspace }}/Qt/ windows desktop tools_ifw qt.tools.ifw.46
          echo "${{ github.workspace }}/Qt/6.4.1/msvc2019_64/bin/" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "${{ github.workspace }}/Qt/Tools/QtInstallerFramework/4.6/bin/" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - name: Install QT dependencies for mac
        if: matrix.os == 'macos-latest'
        shell: bash
        run: |
          pip install aqtinstall
          python -m aqt install-qt -O ${{ github.workspace }}/Qt/ mac desktop 6.4.1 clang_64
          python -m aqt install-tool -O ${{ github.workspace }}/Qt/ mac desktop tools_ifw qt.tools.ifw.46
          echo "${{ github.workspace }}/Qt/6.4.1/clang_64/bin/" >> $GITHUB_PATH
          echo "${{ github.workspace }}/Qt/Tools/QtInstallerFramework/4.6/bin/" >> $GITHUB_PATH
          conda install -c conda-forge liblsl -y
      - name: Install explorepy depencies and necessary packages
        run: |
          pip install pyinstaller
          pip install eeglabio
          pip install mne
          pip install -e .
      - name: Use develop branch if specified
        if: ${{ env.usedevelop == 'true' }} && matrix.os != 'macos-latest'
        run: |
          pip uninstall -y explorepy
          pip install git+https://github.com/Mentalab-hub/explorepy.git@develop
      - name: Use macOS develop branch if on macOS
        if: ${{ env.usemacdevelop == 'true' }} && matrix.os == 'macos-latest'
        run: |
          pip uninstall -y explorepy
          pip install git+https://github.com/Mentalab-hub/explorepy.git@feature-mac-dev
      - name: Build offline app
        run: pyinstaller --noconfirm --distpath ${{ env.exploredesktop_path }}data ExploreDesktop.spec
      - name: Generate installer for Windows
        if: matrix.os == 'windows-latest'
        run: binarycreator.exe -c ${{ env.config_path }} -p ${{ env.package_path }} --verbose ExploreDesktopInstallerOffline.exe
      - name: Generate installer for macOS
        if: matrix.os == 'macos-latest'
        run: |
          mkdir out
          binarycreator -c ${{ env.config_path }} -p ${{ env.package_path }} --verbose ./out/ExploreDesktopInstallerOffline.run
      - name: Upload installer for Windows
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v3
        with:
          name: exploredesktop-installer-windows
          path: ExploreDesktopInstallerOffline.exe
      - name: Zip files for macOS
        if: matrix.os == 'macos-latest'
        run: zip -r ExploreDesktopInstallerOffline.zip out/*
      - name: Upload installer for macOS
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v3
        with:
          name: exploredesktop-installer-mac
          path: ExploreDesktopInstallerOffline.zip