name: release
on:
  pull_request:
    branches: [develop]
jobs:
  release:
    strategy:
      matrix:
        os: [ windows-latest]
        python: [3.8.10]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Conda info
        shell: bash -l {0}
        run: conda info
      - name: Conda list
        shell: pwsh
        run: conda list

#      - name: upload artifact
#        uses: actions/upload-artifact@v2
#        with:
#          name: ExploreGUI_installer_${{ matrix.os }}
#          path: ExploreGUIInstaller.run