name: release
on:
  pull_request:
    branches: [develop]
jobs:
  release:
    strategy:
      matrix:
        os: [ ubuntu-latest]
        python: [3.8.10]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install non-python dependencies on Ubuntu
        run: |
          sudo apt-get update -yq
          # pytest-qt's dependency
          sudo apt-get install -yq libgles2-mesa-dev
          # explorepy's dependency
          sudo apt-get install -yq libbluetooth-dev libpugixml1v5 libxkbcommon-x11-0
          # instal pylsl's dependency
          wget https://github.com/sccn/liblsl/releases/download/v1.15.2/liblsl-1.15.2-focal_amd64.deb
          sudo dpkg -i liblsl-1.15.2-focal_amd64.deb
          sudo apt-get install -yq -f
          # Install tkinter
          sudo apt-get install -yq python3-tk

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: install qt and qt-ifw
        run: |
          python -m pip install --upgrade pip
          # Install qt installer, qt and qt_ifw
          pip install aqtinstall
          aqt install-qt linux desktop 5.12.12 
          aqt install-tool linux desktop tools_ifw
          # Install Pyinstaller
          pip install pyinstaller==4.7
          # Install ExploreGUI
          pip install -e .
          pip list

      - name: Create installer file
        run: |
          pyinstaller --onedir --console --icon=mentalab ExploreGUI.spec
          mv  -v dist/ExploreGUI/* installer/Ubuntu/ExploreGuiInstaller/ExploreGUI/packages/com.Mentalab.ExploreGUI/data/
          ./Tools/QtInstallerFramework/4.2/bin/binarycreator -c installer/Ubuntu/ExploreGuiInstaller/ExploreGUI/config/config.xml -p installer/Ubuntu/ExploreGuiInstaller/ExploreGUI/packages --verbose ExploreGUIInstaller.run
          ls
          python --version

      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ExploreGUI_installer_${{ matrix.os }}
          path: ExploreGUIInstaller.run
