name: release
on:
  pull_request:
    branches: [develop]
jobs:
  release:
    strategy:
      matrix:
        os: [ windows-latest]
        python: [3.8.10]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup miniconda env
        shell: cmd
        run: |
          set PATH=%PATH%;C:\Miniconda\Scripts
          create-setup-file-windows.bat

      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ExploreGUI_installer_${{ matrix.os }}
          path: ExploreGUIInstaller.exe